TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.15
  max_vel_theta: 0.35
  min_vel_theta: -0.35
  min_in_place_vel_theta: 0.15
#  escape_vel: -0.2

#  sim_time: 2.0
  sim_time: 3.0
  sim_granularity: 0.3
#  path_distance_bias: 0.6
#  goal_distance_bias: 0.6

  acc_lim_th: 0.15 #3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: false
  meter_scoring: true

  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.25
